inherit_gem:
  rubocop-shopify: rubocop.yml
require: rubocop-rails

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake}'
    - !ruby/regexp /old_and_unused\.rb$/
  NewCops: enable
