inherit_gem:
  rubocop-shopify: rubocop.yml
require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake}'
    - !ruby/regexp /old_and_unused\.rb$/
  NewCops: enable

Bundler/OrderedGems:
  Enabled: true
Lint/MissingSuper:
  Exclude:
    - 'app/components/**/*'
Rails/I18nLocaleTexts:
  Enabled: false
